# Site settings
title: Leo Ribeiro
description: My resumed portfolio and projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "leordev.github.io"

# User settings
username: Leo Ribeiro
user_description: Hi, I'm Leo Ribeiro! A Brazilian software developer with 14+ years of experience. Father and husband in sunny South Florida. I started developing at 13 years old and since then have worked on a wide range of projects including Android apps, iPhone apps, enterprise software, Web apps and more. I'm constantly expanding my skill set and challenging myself with new languages, tools and technologies so I can better help my clients build what they need and reach their goals.

user_title: Software Engineer
email: leordev@gmail.com
twitter_username: leordev
github_username:  leordev
gplus_username:  leordev

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
